export const QUEUE_STATUS = {
  PENDING: QUEUE_STATUS.PENDING,
  PROCESSING: QUEUE_STATUS.PROCESSING,
  SENT: QUEUE_STATUS.SENT,
  FAILED: QUEUE_STATUS.FAILED,
} as const;

export type QueueStatus =
  (typeof QUEUE_STATUS)[keyof typeof QUEUE_STATUS];
