"use client"

import { useEffect, useState } from "react"
import { createClient } from "@supabase/supabase-js"

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!
)

export default function TasksPage() {
  const [workspace, setWorkspace] = useState<any>(null)
  const [tasks, setTasks] = useState<any[]>([])
  const [error, setError] = useState<string | null>(null)

  async function loadTasks(workspaceId: string) {
    const response = await fetch("/api/tasks/list", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ workspaceId }),
    })

    const data = await response.json()

    if (!response.ok) {
      setError(data.error || "Failed to load tasks")
      return
    }

    setTasks(data.tasks || [])
  }

  useEffect(() => {
    async function load() {
      const {
        data: { session },
      } = await supabase.auth.getSession()

      const workspaceResponse = await fetch("/api/workspace/current", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          userId: session?.user?.id,
          email: session?.user?.email,
        }),
      })

      const workspaceData = await workspaceResponse.json()
      setWorkspace(workspaceData.workspace)

      if (workspaceData.workspace?.id) {
        await loadTasks(workspaceData.workspace.id)
      }
    }

    load()
  }, [])

  return (
    <main className="space-y-8">
      <div>
        <h1 className="text-2xl font-semibold">Tasks</h1>
        <p className="text-sm text-muted-foreground">
          Follow-up tasks generated by CRM actions, AI reply intelligence, and sales workflows.
        </p>
      </div>

      {error && (
        <div className="rounded-xl border p-4 text-sm text-red-600">
          {error}
        </div>
      )}

      <section className="rounded-xl border p-6">
        <h2 className="text-lg font-semibold">Workspace tasks</h2>

        <div className="mt-4 space-y-3">
          {tasks.length === 0 && (
            <p className="text-sm text-muted-foreground">
              No tasks yet. Process an interested reply to create a follow-up task.
            </p>
          )}

          {tasks.map((task) => (
            <div key={task.id} className="rounded-lg border p-4">
              <div className="flex items-start justify-between gap-4">
                <div>
                  <p className="font-medium">{task.title}</p>
                  <p className="text-sm text-muted-foreground">
                    Priority: {task.priority || "normal"} · Status: {task.status || "open"}
                  </p>
                </div>

                <span className="rounded-full border px-3 py-1 text-xs capitalize">
                  {task.status || "open"}
                </span>
              </div>
            </div>
          ))}
        </div>
      </section>
    </main>
  )
}
